Increment #15
m1khal3v/gometheus pull request #15
Opened 2024-07-17 22:28 UTC by m1khal3v

2024-07-22 20:26 UTC, tmvrus requested changes
Работа интересная, но есть ряд вопросов

2024-07-22 20:26 UTC, tmvrus commented on internal/agent/agent.go
> +			panic(err)
так делать не стоит, потому что есть возможность эту ошибку обработать
https://go.dev/wiki/CodeReviewComments#dont-panic

паникой вообще не рекомендую пользоваться, она очень редко когда оправдана

2024-07-22 20:26 UTC, tmvrus commented on internal/agent/agent.go
> +		collector := item
на твоей версии go такой трюк уже можно не делать
https://play.golang.com/p/bS2fDUImg0P

2024-07-22 20:26 UTC, tmvrus commented on pkg/semaphore/semaphore.go
> +}
Если развернуть схему и при Acquire писать в канал а при Release читать то заполнять значениями не придется.

2024-07-22 20:26 UTC, tmvrus commented on pkg/semaphore/semaphore_test.go
> +	require.Error(t, semaphore.Acquire(ctx))
вот это не очень надежно, в большинстве случае оно действительно будет работать, но может случится так что не пройдет одной миллисекунды и тест рухнет. Рекомендую переписать это так:
- создаем WithCancel
- отменяем сразу в не в defer
- пытемся получить семафор на отмененном контексте, получаем ошибку
такой тест будет стабильно работать.

2024-07-22 20:26 UTC, tmvrus commented on internal/agent/agent.go
> +		errGroup.Go(func() error {
тут есть вопрос, чисто теоретически, может случится так, что  семафор мы взять успеем а вот запустить Go  - нет, тогда результат будет непредсказуемым. Я бы рекомендовал брать семафор внутри той же ф-и где он и возвращается.

2024-07-22 21:02 UTC, m1khal3v commented
@tmvrus пока ждал ревью нашел еще немного багов, которые за счет того что автотесты не прогонялись на iter15 ветке - не было видно, поэтому тут еще правки подъехали) Из значительного: коммент на №14 автотест, ErrDeadlock в manager.go. Еще понял, что есть такая проблема что из-за Retry в клиенте и возврате метрик обратно в очередь может нарушиться порядок отправки метрик и из-за этого данные будут не совсем валидные. Можно к метрике добавлять timestamp прямо в коллекторах, а на стороне сервера хранить историю и отдавать метрики с MAX(timestamp), или можно на стороне агента хранить небольшой кэш Name=>timestamp отбрасывая метрики gauge у которых метка меньше последней + чистить этот кэш как только очередь пустеет

2024-07-23 06:51 UTC, tmvrus approved these changes

2024-07-23 10:07 UTC, merged