Increment #5
m1khal3v/gometheus pull request #5
Opened 2024-06-05 07:40 UTC by m1khal3v

2024-06-05 13:49 UTC, tmvrus requested changes
есть над чем подумать

2024-06-05 13:49 UTC, tmvrus commented on cmd/agent/main.go
> +
вот эти переменные дублирую уже существующий поля структуры. это не обязательно, можно передавать в flag.StringVarP, flag.Uint32VarP

а что бы совсем отказаться от глобальных переменных рекомендую сделать ф-у
func parseConfig() Cofnfig 
и пользоваться ей вместо init

2024-06-05 13:49 UTC, tmvrus commented on cmd/server/main.go
> +}
тут тоже самое что и выше

2024-06-05 13:49 UTC, tmvrus commented on internal/store/metric.go
> +	MetricTypeCounter string = "counter"
тип можно ну указывать, компилятор сам его поймет в таких простых случаях

2024-06-05 13:49 UTC, tmvrus commented on internal/store/metric.go
> +func resolveFloat64Value(metricType string, name string, value float64) (*Metric, error) {
если у аргументов идущих подряд один и тот же тип - его можно указать один раз
(metricType, name string, value float64)

2024-06-05 13:49 UTC, tmvrus commented on internal/store/metric.go
> +package store
этот слой, судя по названию, должен заниматься хранением данных, но он делает все что угодно кроме хранения, зачем так?

2024-06-05 13:49 UTC, tmvrus commented on internal/storage/memory/memory.go
> +	Metrics map[string]*store.Metric
- зачем поле Metrics сделано экспортируемым
- по какой причине используется *store.Metric а не store.Metric?

2024-06-05 13:49 UTC, tmvrus commented on internal/route/save_metric_route.go
> +	}
это больше похоже на badrequest ведь имя метрики не передали

2024-06-05 13:49 UTC, tmvrus commented on internal/storage/storage.go
> +type MetricNotFoundError struct {
ошибки принято писать префиксом ErrXXX
<img width="526" alt="image" src="https://github.com/m1khal3v/gometheus/assets/554425/e32c69e6-14ce-4889-8650-283576d12c51">

2024-06-05 13:49 UTC, tmvrus commented on internal/collector/random/random.go
> +func (collector *Collector) Collect() ([]*store.Metric, error) {
а эта ф-я никогда не возвращает ошибку

2024-06-05 13:49 UTC, tmvrus commented on internal/collector/random/random.go
> +		rand.Float64()*(collector.Max-collector.Min)+collector.Min,
вот эта математика требует пояснения

2024-06-05 13:49 UTC, tmvrus commented on internal/collector/runtime/runtime.go
> +func (collector *Collector) Collect() ([]*store.Metric, error) {
эта ф-я никогда не возвращет ошибку

2024-06-05 13:49 UTC, tmvrus commented on internal/collector/collector.go
> +	Collect() ([]*store.Metric, error)
ни одни из реализаций не возвращает ошибку, зачем тогда?

2024-06-05 13:49 UTC, tmvrus commented on internal/agent/agent.go
> +	}
эт прям некрасиво
можно запустить колектор в горутине а отправлятель без горутины тогда не нужен будет цикл

2024-06-05 20:47 UTC, m1khal3v commented on cmd/agent/main.go
> +
Да, так стало значительно лучше

2024-06-05 20:47 UTC, m1khal3v commented on internal/store/metric.go
> +func resolveFloat64Value(metricType string, name string, value float64) (*Metric, error) {
Вроде везде поправил

2024-06-05 21:06 UTC, m1khal3v commented on internal/store/metric.go
> +package store
Тут я исходил из того что storage это хранилище, а store это что-то вроде ассортимент, поменял на metric

2024-06-05 21:09 UTC, m1khal3v commented on internal/collector/random/random.go
> +func (collector *Collector) Collect() ([]*store.Metric, error) {
отвечу в интерфейсе

2024-06-05 21:09 UTC, m1khal3v commented on internal/collector/random/random.go
> +		rand.Float64()*(collector.Max-collector.Min)+collector.Min,
добавил коммент

2024-06-05 21:10 UTC, m1khal3v commented on internal/collector/runtime/runtime.go
> +func (collector *Collector) Collect() ([]*store.Metric, error) {
отвечу в интерфейсе

2024-06-05 21:11 UTC, m1khal3v commented on internal/collector/collector.go
> +	Collect() ([]*store.Metric, error)
random collector возвращает

2024-06-05 21:11 UTC, m1khal3v commented on internal/agent/agent.go
> +	}
поправил

2024-06-05 21:12 UTC, m1khal3v commented on internal/storage/storage.go
> +type MetricNotFoundError struct {
поправил

2024-06-05 21:13 UTC, m1khal3v commented on internal/route/save_metric_route.go
> +	}
в задании первого инкремента сказано

> При попытке передать запрос без имени метрики возвращать http.StatusNotFound.

2024-06-05 21:14 UTC, m1khal3v commented on internal/storage/memory/memory.go
> +	Metrics map[string]*store.Metric
поправил. если я правильно понял, то тут суть в том что после сохранения в хранилище объект должен быть имутабельным и меняться только под контролем интерфейса предоставляемого хранилищем

2024-06-05 21:17 UTC, m1khal3v commented on internal/store/metric.go
> +	MetricTypeCounter string = "counter"
Поправил

2024-06-05 21:21 UTC, m1khal3v commented on internal/collector/collector.go
> +	Collect() ([]*store.Metric, error)
в теории мы можем добавить какой-нибудь коллектор метрик одной из СУБД, которые как минимум могут возвращать ошибку о недоступности сервера, поэтому заложил это в интерфейсе

2024-06-07 11:46 UTC, tmvrus commented on internal/route/save_metric_route.go
> +	}
да, им я тоже писал что это не ок)

2024-06-07 11:47 UTC, tmvrus approved these changes

2024-06-07 12:08 UTC, merged